package com.bank.islamic.ujrahcardservices;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Ujrah Card Services
 *
 * Business Area:      Takaful and Shared Operations
 * Business Domain:    Islamic Cards and Payments
 * Functional Pattern: Fulfill
 * Asset Type:         Ujrah Card Facility
 * Control Record:     Ujrah Card Facility Fulfillment Arrangement
 *
 * Generated by the islamic-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Ujrah Card Services — BIAN Semantic API")
                .description("Service Domain 'Ujrah Card Services' (Fulfill pattern) "
                        + "operating on the 'Ujrah Card Facility Fulfillment Arrangement' control record.")
                .version("0.1.0"));
    }
}
